// src/scaffold/templates.ts
// Plantillas de archivos base por tipo de stack.
// Cada plantilla es un Record<relativePath, fileContent>.
// V2 extension: agregar plantillas para mobile, python, etc.

export type StackTemplate = Record<string, string>;

// ─── Archivos comunes a todos los proyectos ───────────────────────

export const commonFiles: StackTemplate = {
  ".env.example": `# Environment variables
NODE_ENV=development
PORT=3000
`,
  ".gitignore": `node_modules/
dist/
.env
.DS_Store
*.log
coverage/
.next/
`,
  "README.md": `# Project

Generated by ORQUESTADOR-PRIME scaffold.

## Setup

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`
`,
};

// ─── Next.js (SaaS, Dashboard, ERP) ──────────────────────────────

export const nextjsTemplate: StackTemplate = {
  "package.json": JSON.stringify({
    name: "project",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      next: "^15.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
    },
    devDependencies: {
      typescript: "^5.0.0",
      "@types/node": "^20.0.0",
      "@types/react": "^19.0.0",
    },
  }, null, 2),

  "tsconfig.json": JSON.stringify({
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    exclude: ["node_modules"],
  }, null, 2),

  "src/app/layout.tsx": `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by ORQUESTADOR-PRIME",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  "src/app/page.tsx": `export default function Home() {
  return (
    <main>
      <h1>Welcome</h1>
    </main>
  );
}
`,
  "src/app/api/health/route.ts": `import { NextResponse } from "next/server";

export function GET() {
  return NextResponse.json({ status: "ok", timestamp: new Date().toISOString() });
}
`,
  "src/lib/utils.ts": `export function cn(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}
`,
  "src/types/index.ts": `// Shared type definitions
export interface ApiResponse<T> {
  data: T;
  error?: string;
}
`,
};

// ─── Express API ──────────────────────────────────────────────────

export const expressTemplate: StackTemplate = {
  "package.json": JSON.stringify({
    name: "api",
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "tsx watch src/index.ts",
      build: "tsc",
      start: "node dist/index.js",
    },
    dependencies: {
      express: "^4.18.0",
      dotenv: "^16.0.0",
      zod: "^3.22.0",
    },
    devDependencies: {
      typescript: "^5.0.0",
      tsx: "^4.0.0",
      "@types/express": "^4.17.0",
      "@types/node": "^20.0.0",
    },
  }, null, 2),

  "src/index.ts": `import express from "express";
import "dotenv/config";

const app  = express();
const port = process.env["PORT"] ?? 3000;

app.use(express.json());

app.get("/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

app.listen(port, () => {
  console.log(\`Server running on port \${port}\`);
});
`,
  "src/routes/index.ts": `import { Router } from "express";

const router = Router();

export default router;
`,
  "src/middleware/errorHandler.ts": `import type { Request, Response, NextFunction } from "express";

export function errorHandler(
  err: Error,
  _req: Request,
  res: Response,
  _next: NextFunction
) {
  console.error(err.stack);
  res.status(500).json({ error: "Internal server error" });
}
`,
  "src/types/index.ts": `export interface ApiResponse<T> {
  data: T;
  error?: string;
}
`,
};

// ─── Selector por tipo de proyecto ───────────────────────────────

import type { ProjectType } from "../types.js";

export function selectTemplate(projectType: ProjectType): StackTemplate {
  switch (projectType) {
    case "saas":
    case "dashboard":
    case "erp":
      return { ...commonFiles, ...nextjsTemplate };
    case "api":
      return { ...commonFiles, ...expressTemplate };
    case "ecommerce":
      return { ...commonFiles, ...nextjsTemplate };
    case "landing":
      return { ...commonFiles, ...nextjsTemplate };
    case "generic":
    default:
      return { ...commonFiles, ...nextjsTemplate };
  }
}