import {
  type ModuleLayer,
  type ModuleLayerDescription,
} from "./moduleBoundaries.js";

const allLayers: ModuleLayer[] = [
  "core",
  "pm",
  "architecture",
  "autopilot",
  "integrations",
  "whatsapp",
  "viernesBridge",
  "dashboard",
  "scripts",
  "docs",
  "tests",
  "providers",
  "config",
  "runtime_future",
];

const makeLayer = (
  layer: ModuleLayer,
  label: string,
  safeSummary: string,
  allowedTargets: ModuleLayer[],
  reviewRequiredTargets: ModuleLayer[],
  forbiddenTargets: ModuleLayer[],
  futureGatedTargets: ModuleLayer[],
  rationale: string,
): ModuleLayerDescription => ({
  layer,
  label,
  safeSummary,
  allowedTargets,
  reviewRequiredTargets,
  forbiddenTargets,
  futureGatedTargets,
  rationale,
  metadataOnly: true,
  reportOnly: true,
  advisoryOnly: true,
  sourceOnly: true,
  noScannerExecution: true,
  noRefactorExecution: true,
});

export const buildDefaultLayerMap = (): ModuleLayerDescription[] => [
  makeLayer(
    "core",
    "Core",
    "Stable domain vocabulary and pure helper layer.",
    ["core"],
    ["pm", "architecture"],
    ["integrations", "whatsapp", "viernesBridge", "dashboard", "providers", "config"],
    ["runtime_future"],
    "Core remains independent from live-adjacent and future runtime layers.",
  ),
  makeLayer(
    "pm",
    "Project Manager",
    "Source-only advisory PM metadata layer.",
    ["core", "pm"],
    ["architecture", "autopilot", "scripts", "tests"],
    ["integrations", "whatsapp", "viernesBridge", "providers", "config"],
    ["dashboard", "runtime_future"],
    "PM can describe context but should not depend on execution, provider, or channel surfaces.",
  ),
  makeLayer(
    "architecture",
    "Architecture",
    "Report-only architecture quality metadata layer.",
    ["core", "architecture"],
    ["pm", "autopilot", "scripts", "tests"],
    ["integrations", "whatsapp", "viernesBridge", "dashboard", "providers", "config"],
    ["runtime_future"],
    "Architecture can use metadata vocabulary while avoiding live-adjacent dependencies.",
  ),
  makeLayer(
    "autopilot",
    "Autopilot",
    "Metadata/control support layer for handoff, validation, memory proposals, next action, and closeout.",
    ["core", "autopilot"],
    ["pm", "architecture", "scripts", "tests"],
    ["providers", "dashboard", "whatsapp", "viernesBridge", "integrations", "config"],
    ["runtime_future"],
    "Autopilot remains coordination metadata and must not launch execution surfaces.",
  ),
  makeLayer(
    "integrations",
    "Integrations",
    "Live-adjacent integration layer.",
    ["core", "integrations"],
    ["pm", "architecture", "autopilot"],
    ["dashboard", "providers"],
    ["runtime_future"],
    "Integrations need explicit contracts before crossing into advisory layers.",
  ),
  makeLayer(
    "whatsapp",
    "WhatsApp",
    "Channel bridge layer for WhatsApp flows.",
    ["core", "whatsapp"],
    ["pm", "architecture", "autopilot", "viernesBridge"],
    ["providers", "dashboard"],
    ["runtime_future"],
    "Channel bridges stay isolated unless future contracts approve a boundary.",
  ),
  makeLayer(
    "viernesBridge",
    "Viernes Bridge",
    "Bridge layer for Viernes interoperability.",
    ["core", "viernesBridge"],
    ["pm", "architecture", "autopilot", "whatsapp"],
    ["providers", "dashboard"],
    ["runtime_future"],
    "Viernes bridge boundaries remain explicit and should not bypass advisory gates.",
  ),
  makeLayer(
    "dashboard",
    "Dashboard",
    "User interface and dashboard layer.",
    ["core", "dashboard"],
    ["pm", "architecture", "autopilot"],
    ["providers", "config"],
    ["runtime_future"],
    "Dashboard integration requires future read-only contracts before PM/SOLID display work.",
  ),
  makeLayer(
    "scripts",
    "Scripts",
    "Verification and helper script layer.",
    allLayers,
    [],
    [],
    ["runtime_future"],
    "Scripts may exercise metadata in verification but should not become production dependencies.",
  ),
  makeLayer(
    "docs",
    "Documentation",
    "Documentation and planning layer.",
    allLayers,
    [],
    [],
    ["runtime_future"],
    "Docs may reference all layers as narrative context only.",
  ),
  makeLayer(
    "tests",
    "Tests",
    "Smoke and test metadata layer.",
    allLayers,
    [],
    [],
    ["runtime_future"],
    "Tests may verify source-only contracts without introducing runtime behavior.",
  ),
  makeLayer(
    "providers",
    "Providers",
    "Provider-adjacent layer.",
    ["core", "providers"],
    ["integrations"],
    ["pm", "architecture", "autopilot", "dashboard"],
    ["runtime_future"],
    "Provider dependencies must not leak into source-only advisory layers.",
  ),
  makeLayer(
    "config",
    "Config",
    "Configuration-adjacent layer.",
    ["core", "config"],
    ["integrations", "providers"],
    ["pm", "architecture", "autopilot", "dashboard"],
    ["runtime_future"],
    "Config-sensitive dependencies require future plans and must not enter advisory layers.",
  ),
  makeLayer(
    "runtime_future",
    "Future Runtime",
    "Future-gated runtime layer.",
    [],
    [],
    allLayers.filter((layer) => layer !== "runtime_future"),
    ["runtime_future"],
    "Runtime remains future-gated during the SOLID architecture block.",
  ),
];

export const defaultModuleLayerMap = buildDefaultLayerMap();
