import type { StoreInventoryEntry } from "./types.js";

const VERSION_1 = "1.0";

export const STORE_INVENTORY: StoreInventoryEntry[] = [
  {
    storeId: "user-config",
    displayName: "User config",
    fileName: "config.json",
    scope: "global",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    sensitiveFields: ["hookToken", "allowedPhones", "providers"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "global-config",
  },
  {
    storeId: "workspace",
    displayName: "Workspace store",
    fileName: "workspaces.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["projects"],
    sensitiveFields: ["facts", "decisions", "contextMap"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "workspace",
  },
  {
    storeId: "memory-v1",
    displayName: "Legacy memory store",
    fileName: "memory.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["entries"],
    sensitiveFields: ["task", "keywords"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "memory",
  },
  {
    storeId: "memory-v2",
    displayName: "Memory V2 store",
    fileName: "memory-v2.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["entries"],
    sensitiveFields: ["summary", "safePreview", "links"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "memory",
  },
  {
    storeId: "permissions",
    displayName: "Permission grants",
    fileName: "permissions.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["grants"],
    sensitiveFields: ["subjectHash", "conditions"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "permissions",
  },
  {
    storeId: "permission-audit",
    displayName: "Permission audit",
    fileName: "permission-audit.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["entries"],
    sensitiveFields: ["subjectHash", "safeMessage"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "permissions",
  },
  {
    storeId: "action-proposals",
    displayName: "Action proposals",
    fileName: "actions.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["proposals"],
    sensitiveFields: ["parameters", "description", "sourceEventId"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "actions",
  },
  {
    storeId: "action-executions",
    displayName: "Action execution results",
    fileName: "action-executions.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["results"],
    sensitiveFields: ["output", "message"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "actions",
  },
  {
    storeId: "second-approvals",
    displayName: "Second approvals",
    fileName: "action-second-approvals.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["approvals"],
    sensitiveFields: ["grantedBy", "proposalParameterHash"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "actions",
  },
  {
    storeId: "channel-audit",
    displayName: "Channel audit",
    fileName: "channel-audit.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["entries"],
    sensitiveFields: ["principalHash", "sourceEventId", "reason"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "channels",
  },
  {
    storeId: "jobs",
    displayName: "Jobs",
    fileName: "jobs.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["jobs"],
    sensitiveFields: ["safeInput", "inputPreview", "subjectHash"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "jobs",
  },
  {
    storeId: "notifications",
    displayName: "Notifications",
    fileName: "notifications.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["notifications"],
    sensitiveFields: ["title", "summary", "links"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "notifications",
  },
  {
    storeId: "trajectories",
    displayName: "Trajectories",
    fileName: "trajectories.json",
    scope: "mixed",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["trajectories"],
    sensitiveFields: ["userMessage", "providerCalls", "toolCalls"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "trajectories",
  },
  {
    storeId: "multi-agent-traces",
    displayName: "Multi-agent traces",
    fileName: "multi-agent-traces.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["traces"],
    sensitiveFields: ["requestPreview", "artifactPreview", "reviews"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "multi-agent",
  },
  {
    storeId: "supervisor-goals",
    displayName: "Supervisor goals",
    fileName: "supervisor-goals.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["projects"],
    sensitiveFields: ["description", "riskNotes"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "supervisor",
  },
  {
    storeId: "screenshot-traces",
    displayName: "Screenshot traces",
    fileName: "screenshot-traces.json",
    scope: "project-scoped",
    required: false,
    expectedVersion: VERSION_1,
    versionField: "version",
    collectionFields: ["traces"],
    sensitiveFields: ["windowTitlePreview", "screenshotRef", "urlHost"],
    futureMigrationVersion: VERSION_1,
    futureLockScope: "computer-use",
  },
];

export function getStoreInventory(): StoreInventoryEntry[] {
  return STORE_INVENTORY.map((entry) => {
    const cloned: StoreInventoryEntry = { ...entry };
    if (entry.collectionFields) {
      cloned.collectionFields = entry.collectionFields.slice();
    }
    if (entry.sensitiveFields) {
      cloned.sensitiveFields = entry.sensitiveFields.slice();
    }
    return cloned;
  });
}
