import type {
  OpenClawCapabilityEntry,
  OpenClawCapabilityId,
} from "./capabilityTypes.js";

export const OPENCLAW_CAPABILITY_REGISTRY = [
  {
    capabilityId: "computer.inspect.plan",
    openclawTool: null,
    action: "inspect",
    description: "Plan a read-only inspection of visible computer context.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["metadata", "browser", "application", "desktop"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.screenshot.metadata",
    openclawTool: null,
    action: "screenshot-metadata",
    description: "Store metadata about a screenshot trace without raw image data.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["metadata"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.click.plan",
    openclawTool: null,
    action: "click",
    description: "Describe where a click would happen without moving the mouse.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: true,
    requiresKeyboard: false,
    requiresMouse: true,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["browser", "application", "desktop"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.type.plan",
    openclawTool: null,
    action: "type",
    description: "Describe text entry without sending keystrokes.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: true,
    requiresKeyboard: true,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["browser", "application", "desktop"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.navigate.plan",
    openclawTool: null,
    action: "navigate",
    description: "Describe navigation without opening URLs or controlling apps.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["browser", "application"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "openclaw.tool_invoke.dry_run",
    openclawTool: "tools.invoke",
    action: "tool-invoke",
    description: "Describe an OpenClaw tool invocation request without calling the gateway.",
    riskLevel: "review-required",
    dryRunSupported: true,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["tool-gateway"],
    requiredPermissions: ["openclaw.tool_invoke.dry_run"],
    requiredEnv: ["OPENCLAW_GATEWAY_TOKEN"],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.click.real",
    openclawTool: null,
    action: "click",
    description: "Future real click capability. Disabled in this block.",
    riskLevel: "forbidden",
    dryRunSupported: false,
    realExecutionSupported: false,
    requiresScreenshot: true,
    requiresKeyboard: false,
    requiresMouse: true,
    requiresNetwork: false,
    mutatesExternalState: true,
    mutatesRepo: false,
    allowedTargets: ["browser", "application", "desktop"],
    requiredPermissions: [],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.type.real",
    openclawTool: null,
    action: "type",
    description: "Future real typing capability. Disabled in this block.",
    riskLevel: "forbidden",
    dryRunSupported: false,
    realExecutionSupported: false,
    requiresScreenshot: true,
    requiresKeyboard: true,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: true,
    mutatesRepo: false,
    allowedTargets: ["browser", "application", "desktop"],
    requiredPermissions: [],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.navigate.real",
    openclawTool: null,
    action: "navigate",
    description: "Future real navigation capability. Disabled in this block.",
    riskLevel: "forbidden",
    dryRunSupported: false,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: true,
    mutatesExternalState: true,
    mutatesRepo: false,
    allowedTargets: ["browser", "application"],
    requiredPermissions: [],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "computer.screenshot.raw",
    openclawTool: null,
    action: "screenshot-metadata",
    description: "Future raw screenshot storage. Disabled in this block.",
    riskLevel: "forbidden",
    dryRunSupported: false,
    realExecutionSupported: false,
    requiresScreenshot: true,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: false,
    mutatesExternalState: false,
    mutatesRepo: false,
    allowedTargets: ["desktop"],
    requiredPermissions: [],
    requiredEnv: [],
    forbiddenByDefault: true,
  },
  {
    capabilityId: "openclaw.tool_invoke.real",
    openclawTool: "tools.invoke",
    action: "tool-invoke",
    description: "Future real OpenClaw gateway tool invocation. Disabled in this block.",
    riskLevel: "forbidden",
    dryRunSupported: false,
    realExecutionSupported: false,
    requiresScreenshot: false,
    requiresKeyboard: false,
    requiresMouse: false,
    requiresNetwork: true,
    mutatesExternalState: true,
    mutatesRepo: false,
    allowedTargets: ["tool-gateway"],
    requiredPermissions: [],
    requiredEnv: ["OPENCLAW_GATEWAY_TOKEN"],
    forbiddenByDefault: true,
  },
] as const satisfies readonly OpenClawCapabilityEntry[];

function cloneCapability(entry: OpenClawCapabilityEntry): OpenClawCapabilityEntry {
  return {
    ...entry,
    allowedTargets: entry.allowedTargets.slice(),
    requiredPermissions: entry.requiredPermissions.slice(),
    requiredEnv: entry.requiredEnv.slice(),
  };
}

export function listOpenClawCapabilities(): OpenClawCapabilityEntry[] {
  return OPENCLAW_CAPABILITY_REGISTRY.map(cloneCapability);
}

export function getOpenClawCapability(
  capabilityId: string,
): OpenClawCapabilityEntry | null {
  const entry = OPENCLAW_CAPABILITY_REGISTRY.find(
    (item) => item.capabilityId === capabilityId,
  );
  return entry ? cloneCapability(entry) : null;
}

export function isOpenClawCapabilityDryRunOnly(
  capabilityId: OpenClawCapabilityId | string,
): boolean {
  const entry = getOpenClawCapability(capabilityId);
  return !!entry && entry.dryRunSupported && !entry.realExecutionSupported;
}

export function isOpenClawCapabilityForbiddenByDefault(
  capabilityId: OpenClawCapabilityId | string,
): boolean {
  return getOpenClawCapability(capabilityId)?.forbiddenByDefault ?? true;
}
