import {
  createEndToEndManualAction,
  createEndToEndManualLoopStage,
  createEndToEndManualLoopTrial,
  type EndToEndManualAction,
  type EndToEndManualLoopStage,
  type EndToEndManualLoopTrial,
  type EndToEndManualLoopTrialInput,
} from "./endToEndManualLoopTrial.js";

export const endToEndManualLoopIdeaFixture =
  "Quiero una app movil de habitos gamificada con mundo vivo, progreso, recordatorios y premium futuro.";

export const endToEndManualLoopExpectedArtifactChainFixture = [
  "conversational_dry_run_metadata",
  "intake_summary",
  "requirements_summary",
  "feature_blueprint_summary",
  "screen_blueprint_summary",
  "api_contract_candidate_summary",
  "design_system_summary",
  "quality_security_release_summary",
  "store_readiness_summary",
  "prompt_draft_metadata",
  "human_approved_handoff_package",
  "manual_copy_metadata",
  "human_submitted_report_metadata",
  "controlled_report_return_metadata",
  "report_validation_metadata",
  "next_action_metadata",
  "phase_closeout_metadata",
  "human_facing_response_metadata",
] as const;

export const endToEndManualLoopExpectedReportShapeFixture = [
  "phase",
  "files inspected",
  "files modified",
  "implementation or plan summary",
  "safety guarantees",
  "tests/scripts",
  "commands executed",
  "scope check",
  "forbidden grep",
  "commit/push",
  "next recommended phase",
] as const;

export const endToEndManualLoopTrialInputFixture: EndToEndManualLoopTrialInput = {
  trialId: "end_to_end_manual_loop:habit_world_trial",
  userIdeaText: endToEndManualLoopIdeaFixture,
  sourceDryRunRef: "conversational_build_loop:habit_world_v1",
  handoffRef: "human_approved_codex_handoff:habit_world_v1",
  targetCodexPhase: "TRIAL-1B - SAMPLE MOBILE IDEA BLUEPRINT DRY-RUN PLAN",
  targetCodexMode: "B",
  manualCopyRequired: true,
  manualReportReturnRequired: true,
  expectedArtifactChain: endToEndManualLoopExpectedArtifactChainFixture,
  expectedReportShape: endToEndManualLoopExpectedReportShapeFixture,
  expectedValidationStatus: "passed",
  expectedCloseoutStatus: "completed_local_only",
  expectedNextAction: "TRIAL-1I - SAMPLE MOBILE IDEA BLUEPRINT DRY-RUN IMPLEMENTATION",
  riskLevel: "plan_only",
  requiredApprovals: [
    "human_operator_copy_approval",
    "human_operator_report_return",
    "pm_scope_review",
    "safety_closeout_review",
  ],
  limitations: [
    "manual_steps_are_human_supplied_metadata",
    "no_live_external_session_observation",
    "no_source_driven_external_action",
    "no_memory_persistence",
  ],
};

export const endToEndManualLoopDefaultStagesFixture: readonly EndToEndManualLoopStage[] = [
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:create_dry_run",
    stageName: "create_dry_run",
    inputRefs: ["user_idea:habit_world"],
    outputRefs: ["conversational_build_loop:habit_world_v1"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["dry_run:artifact_chain_complete"],
    limitations: ["metadata_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:generate_prompt_draft",
    stageName: "generate_prompt_draft",
    inputRefs: ["conversational_build_loop:habit_world_v1"],
    outputRefs: ["prompt_draft:habit_world_v1"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["prompt_draft:safe_to_use_false"],
    limitations: ["prompt_text_is_metadata_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:validate_handoff",
    stageName: "validate_handoff",
    inputRefs: ["prompt_draft:habit_world_v1"],
    outputRefs: ["human_approved_handoff:habit_world_v1"],
    humanActionRequired: true,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["handoff:safety_complete", "handoff:completeness_complete"],
    limitations: ["human_review_required"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:approve_for_copy",
    stageName: "approve_for_copy",
    inputRefs: ["human_approved_handoff:habit_world_v1"],
    outputRefs: ["handoff_status:approved_for_copy"],
    humanActionRequired: true,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["approval:approved_for_copy"],
    limitations: ["approval_is_metadata_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:manual_copy_to_codex",
    stageName: "manual_copy_to_codex",
    inputRefs: ["handoff_status:approved_for_copy"],
    outputRefs: ["manual_action:copy_prompt"],
    humanActionRequired: true,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["manual_copy:human_confirmed"],
    limitations: ["manual_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:manual_codex_execution",
    stageName: "manual_codex_execution",
    inputRefs: ["manual_action:copy_prompt"],
    outputRefs: ["manual_action:run_codex_manually"],
    humanActionRequired: true,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["manual_run:human_confirmed"],
    limitations: ["external_manual_action_metadata_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:manual_report_return",
    stageName: "manual_report_return",
    inputRefs: ["manual_action:run_codex_manually"],
    outputRefs: ["manual_action:paste_codex_report_back"],
    humanActionRequired: true,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["report_return:human_submitted"],
    limitations: ["manual_report_text_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:normalize_report",
    stageName: "normalize_report",
    inputRefs: ["report_return:human_submitted"],
    outputRefs: ["controlled_report_return:normalized"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["normalized_report:required_sections_present"],
    limitations: ["metadata_normalization_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:validate_report",
    stageName: "validate_report",
    inputRefs: ["controlled_report_return:normalized"],
    outputRefs: ["controlled_report_return:validation"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["validation:no_alert"],
    limitations: ["metadata_validation_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:generate_next_action",
    stageName: "generate_next_action",
    inputRefs: ["controlled_report_return:validation"],
    outputRefs: ["next_action:trial_1i"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["next_action:produced"],
    limitations: ["recommendation_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:generate_closeout",
    stageName: "generate_closeout",
    inputRefs: ["controlled_report_return:validation", "next_action:trial_1i"],
    outputRefs: ["closeout:completed_local_only"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["closeout:completed_local_only"],
    limitations: ["metadata_closeout_only"],
  }),
  createEndToEndManualLoopStage({
    stageId: "end_to_end_stage:render_human_response",
    stageName: "render_human_response",
    inputRefs: ["closeout:completed_local_only"],
    outputRefs: ["human_response:trial_summary"],
    humanActionRequired: false,
    automationAllowed: false,
    blockingConditions: [],
    riskLevel: "plan_only",
    evidenceRefs: ["human_response:rendered"],
    limitations: ["response_metadata_only"],
  }),
] as const;

export const endToEndManualLoopDefaultActionsFixture: readonly EndToEndManualAction[] = [
  createEndToEndManualAction({
    actionId: "end_to_end_action:copy_prompt",
    actionType: "copy_prompt",
    requiredHuman: true,
    instruction: "Human reviews the approved prompt package and transfers it manually.",
    expectedEvidence: ["handoff:approved_for_copy", "copy_claim:human_confirmed"],
    safetyWarning: "Do not use source-driven transfer helpers.",
    allowedAutomationLevel: "manual_only",
    completionClaim: "human_confirmed",
    riskLevel: "plan_only",
    limitations: ["manual_only"],
  }),
  createEndToEndManualAction({
    actionId: "end_to_end_action:paste_prompt_to_codex",
    actionType: "paste_prompt_to_codex",
    requiredHuman: true,
    instruction: "Human places the prompt in the intended separate Codex session.",
    expectedEvidence: ["destination:separate_codex_session", "session:human_confirmed"],
    safetyWarning: "Abort if the destination session is uncertain.",
    allowedAutomationLevel: "manual_only",
    completionClaim: "human_confirmed",
    riskLevel: "plan_only",
    limitations: ["manual_only"],
  }),
  createEndToEndManualAction({
    actionId: "end_to_end_action:run_codex_manually",
    actionType: "run_codex_manually",
    requiredHuman: true,
    instruction: "Human starts and supervises the separate Codex task.",
    expectedEvidence: ["run_claim:human_confirmed", "safe_target_phase:docs_or_metadata_only"],
    safetyWarning: "Source helpers must not invoke the external task.",
    allowedAutomationLevel: "manual_only",
    completionClaim: "human_confirmed",
    riskLevel: "plan_only",
    limitations: ["external_manual_action_metadata_only"],
  }),
  createEndToEndManualAction({
    actionId: "end_to_end_action:paste_codex_report_back",
    actionType: "paste_codex_report_back",
    requiredHuman: true,
    instruction: "Human submits the structured report text back into the local review flow.",
    expectedEvidence: ["report_text:human_submitted", "report_shape:required_sections"],
    safetyWarning: "Report text is supplied by the human; it is not retrieved from a live session.",
    allowedAutomationLevel: "manual_only",
    completionClaim: "human_confirmed",
    riskLevel: "plan_only",
    limitations: ["manual_report_return_only"],
  }),
  createEndToEndManualAction({
    actionId: "end_to_end_action:approve_next_phase",
    actionType: "approve_next_phase",
    requiredHuman: true,
    instruction: "Human reviews closeout and explicitly approves the next phase recommendation.",
    expectedEvidence: ["closeout:completed_local_only", "next_action:trial_1i"],
    safetyWarning: "Do not advance on blocked or unsafe closeout metadata.",
    allowedAutomationLevel: "manual_only",
    completionClaim: "human_confirmed",
    riskLevel: "plan_only",
    limitations: ["human_approval_required"],
  }),
] as const;

export const endToEndManualLoopSuccessFixture: EndToEndManualLoopTrial =
  createEndToEndManualLoopTrial({
    trial: endToEndManualLoopTrialInputFixture,
    stages: endToEndManualLoopDefaultStagesFixture,
    manualActions: endToEndManualLoopDefaultActionsFixture,
    promptDraftPresent: true,
    handoffApprovedForCopy: true,
    safeToExecute: false,
    reportValidationStatus: "passed",
    closeoutStatus: "completed_local_only",
    nextActionProduced: true,
    sourceSideExecutionAbsent: true,
  });

export const endToEndManualLoopBlockedMissingApprovalFixture: EndToEndManualLoopTrial =
  createEndToEndManualLoopTrial({
    trial: {
      ...endToEndManualLoopTrialInputFixture,
      trialId: "end_to_end_manual_loop:blocked_missing_approval",
    },
    stages: endToEndManualLoopDefaultStagesFixture,
    manualActions: endToEndManualLoopDefaultActionsFixture.map((action) =>
      action.actionType === "copy_prompt"
        ? createEndToEndManualAction({
            ...action,
            actionId: "end_to_end_action:copy_prompt_blocked",
            completionClaim: "blocked_missing_approval",
          })
        : action,
    ),
    promptDraftPresent: true,
    handoffApprovedForCopy: false,
    safeToExecute: false,
    reportValidationStatus: "passed",
    closeoutStatus: "needs_human_review",
    nextActionProduced: false,
    sourceSideExecutionAbsent: true,
  });

export const endToEndManualLoopBlockedUnsafeReportFixture: EndToEndManualLoopTrial =
  createEndToEndManualLoopTrial({
    trial: {
      ...endToEndManualLoopTrialInputFixture,
      trialId: "end_to_end_manual_loop:blocked_unsafe_report",
    },
    stages: endToEndManualLoopDefaultStagesFixture,
    manualActions: endToEndManualLoopDefaultActionsFixture,
    promptDraftPresent: true,
    handoffApprovedForCopy: true,
    safeToExecute: false,
    reportValidationStatus: "blocked",
    closeoutStatus: "unsafe_scope",
    nextActionProduced: false,
    sourceSideExecutionAbsent: true,
  });

export const endToEndManualLoopExpectedOutcomeFixture = {
  trialStatus: "completed",
  closeoutStatus: "completed_local_only",
  safeToContinue: true,
  nextRecommendedPhase: "TRIAL-1I - SAMPLE MOBILE IDEA BLUEPRINT DRY-RUN IMPLEMENTATION",
} as const;
