// src/execution/githubClient.ts
// GitHub API usando @octokit/rest.
// Crea PRs, comenta, lista issues.
// Solo activo si GITHUB_TOKEN está configurado.

import { Octokit }        from "@octokit/rest";
import { GITHUB_CONFIG }  from "../config.js";
import { logger }         from "../observability/logger.js";

let _octokit: Octokit | null = null;

function getOctokit(): Octokit {
  if (!_octokit) {
    if (!GITHUB_CONFIG.token) {
      throw new Error(
        "GITHUB_TOKEN is not set. GitHub integration is unavailable."
      );
    }
    _octokit = new Octokit({ auth: GITHUB_CONFIG.token });
  }
  return _octokit;
}

export interface PullRequestOptions {
  title:     string;
  body:      string;
  head:      string;   // branch con los cambios
  base:      string;   // branch destino (normalmente "dev")
  draft?:    boolean;
}

export interface PullRequestResult {
  url:    string;
  number: number;
}

// Abre un Pull Request — siempre como draft por seguridad
export async function createPullRequest(
  options: PullRequestOptions
): Promise<PullRequestResult> {
  const octokit = getOctokit();
  const owner   = GITHUB_CONFIG.owner!;
  const repo    = GITHUB_CONFIG.repo!;

  const pr = await octokit.pulls.create({
    owner,
    repo,
    title: options.title,
    body:  options.body,
    head:  options.head,
    base:  options.base,
    draft: options.draft ?? true,   // draft por defecto — human approval required
  });

  logger.info(`PR opened: #${pr.data.number} — ${pr.data.html_url}`);

  return {
    url:    pr.data.html_url,
    number: pr.data.number,
  };
}

// Agrega un comentario a un PR
export async function commentOnPR(
  prNumber: number,
  body:     string
): Promise<void> {
  const octokit = getOctokit();
  const owner   = GITHUB_CONFIG.owner!;
  const repo    = GITHUB_CONFIG.repo!;

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });

  logger.info(`Comment added to PR #${prNumber}`);
}

// Construye el body del PR con el formato del orquestador
export function buildPRBody(
  task:        string,
  branchName:  string,
  files:       Array<{ path: string; operation: string; reason: string }>,
  risks:       string[],
  rollback:    string,
  traceId:     string
): string {
  const fileLines = files
    .map((f) => `- \`${f.path}\` (${f.operation}): ${f.reason}`)
    .join("\n");

  const riskLines = risks
    .map((r) => `- ${r}`)
    .join("\n");

  return `
## 🤖 ORQUESTADOR-PRIME — Execution Proposal

**Task:** ${task}
**Branch:** \`${branchName}\`
**Trace:** \`${traceId}\`

---

### 📁 Files Changed

${fileLines}

---

### ⚠️ Risks

${riskLines}

---

### 🔄 Rollback Plan

${rollback}

---

> This PR was generated by ORQUESTADOR-PRIME.
> **Human approval required before merge.**
> Review all changes carefully before approving.
`.trim();
}