import type {
  BusinessSystemFamily,
  BusinessSystemFamilyId,
  BusinessSystemIntegration,
  BusinessSystemMetadataItem,
  BusinessSystemWorkflow,
} from "./types.js";

export const REQUIRED_BUSINESS_SYSTEM_FAMILY_IDS = [
  "mvc",
  "erp",
  "crm",
  "pos",
  "bi",
  "bpm",
  "cms",
  "hrms",
  "scm",
  "lms",
  "ecommerce",
  "inventory",
  "accounting-billing",
  "document-management",
  "project-management",
] as const satisfies readonly BusinessSystemFamilyId[];

const item = (
  id: string,
  name: string,
  description: string,
  tags?: string[],
): BusinessSystemMetadataItem => ({
  id,
  name,
  description,
  ...(tags ? { tags } : {}),
});

const workflow = (
  workflowId: string,
  name: string,
  description: string,
  actors: string[],
  steps: string[],
  riskNotes?: string[],
): BusinessSystemWorkflow => ({
  workflowId,
  name,
  description,
  actors,
  steps,
  ...(riskNotes ? { riskNotes } : {}),
});

const integration = (
  integrationId: string,
  name: string,
  type: string,
  description: string,
  riskNotes?: string[],
): BusinessSystemIntegration => ({
  integrationId,
  name,
  type,
  description,
  ...(riskNotes ? { riskNotes } : {}),
});

export const businessSystemsCatalog: readonly BusinessSystemFamily[] = [
  {
    familyId: "mvc",
    name: "MVC systems",
    aliases: ["model-view-controller", "crud web app", "admin web system"],
    purpose:
      "Plan conventional business web systems organized around models, views, controllers, forms, and role-based operations.",
    typicalActors: ["administrator", "operator", "authenticated user", "support user"],
    coreModules: [
      item("controllers", "Controllers", "Request handling and application flow boundaries."),
      item("views", "Views", "Role-aware screens, forms, tables, and dashboards."),
      item("models", "Models", "Logical business objects and validation boundaries."),
      item("auth", "Authentication", "Sign-in, sessions, and account access planning."),
      item("admin", "Administration", "Operator management screens and configuration surfaces."),
      item("crud", "CRUD operations", "Create, read, update, and archive workflows for core records."),
      item("reporting-basics", "Reporting basics", "Operational summaries and exports for review."),
    ],
    commonEntities: [
      item("user", "User", "Authenticated account or operator."),
      item("role", "Role", "Named permission grouping."),
      item("record", "Record", "Primary managed business object."),
      item("audit-event", "Audit event", "Review event for sensitive changes."),
    ],
    workflows: [
      workflow(
        "record-management",
        "Record management",
        "A user creates or updates a managed record through validated screens.",
        ["operator", "administrator"],
        ["Open module", "Validate input", "Save reviewed change", "Record audit note"],
        ["Review destructive updates and retention needs before implementation."],
      ),
    ],
    permissions: [
      item("record-read", "Record read", "View records in allowed scopes."),
      item("record-write", "Record write", "Create and update records after review."),
      item("admin-config", "Admin configuration", "Manage settings and users."),
    ],
    reports: [
      item("activity-summary", "Activity summary", "Shows key record changes and operational counts."),
    ],
    integrations: [
      integration("identity-provider", "Identity provider", "authentication", "Optional sign-in or directory integration."),
    ],
    complianceAndAuditConcerns: [
      "Review access control and audit logging needs before implementation.",
      "Treat retention and export requirements as project-specific checklist items.",
    ],
    dataModelPatterns: ["entity records", "role mappings", "audit event log", "soft archive flags"],
    uiPatterns: ["master-detail screens", "filterable tables", "validated forms", "admin settings"],
    deploymentNotes: ["Plan environment configuration and backup strategy before production use."],
    riskNotes: ["Generic MVC patterns can hide domain-specific workflow rules if requirements are shallow."],
    assumptions: ["A human will review domain rules before any scaffold or implementation phase."],
    tags: ["web", "crud", "admin"],
  },
  {
    familyId: "erp",
    name: "ERP",
    aliases: ["enterprise resource planning", "resource planning"],
    purpose:
      "Plan integrated resource management systems spanning finance, inventory, purchasing, sales, HR, production, and audit concerns.",
    typicalActors: ["finance user", "warehouse user", "sales user", "purchasing user", "manager", "auditor"],
    coreModules: [
      item("finance", "Finance", "Financial planning and operational finance views."),
      item("inventory", "Inventory", "Stock balances, movements, and reconciliation planning."),
      item("sales", "Sales", "Customer orders, sales operations, and fulfillment handoff."),
      item("purchases", "Purchases", "Supplier requests, purchase orders, and receiving."),
      item("hr", "HR", "Employee and organizational data planning."),
      item("production", "Production", "Manufacturing or service production planning where applicable."),
      item("audit", "Audit", "Traceability, approvals, and review support."),
    ],
    commonEntities: [
      item("account", "Account", "Financial account or cost grouping."),
      item("item", "Item", "Product, material, or service."),
      item("warehouse", "Warehouse", "Stock location."),
      item("supplier", "Supplier", "Vendor or procurement partner."),
      item("customer", "Customer", "Buyer or account."),
      item("employee", "Employee", "Worker or internal actor."),
      item("transaction", "Transaction", "Business event requiring traceability."),
    ],
    workflows: [
      workflow(
        "purchase-to-receive",
        "Purchase to receive",
        "A request moves from purchase planning through supplier order and receiving review.",
        ["purchasing user", "warehouse user", "manager"],
        ["Create request", "Review approval need", "Issue purchase order", "Receive goods", "Reconcile variance"],
        ["Financial and inventory impacts require explicit review gates."],
      ),
    ],
    permissions: [
      item("finance-review", "Finance review", "View and review financial planning data."),
      item("inventory-adjust", "Inventory adjustment", "Request or approve stock adjustments."),
      item("audit-read", "Audit read", "Inspect traceability and history."),
    ],
    reports: [
      item("inventory-valuation", "Inventory valuation", "Summary of stock value by item and location."),
      item("purchase-variance", "Purchase variance", "Planned versus received procurement differences."),
    ],
    integrations: [
      integration("accounting-suite", "Accounting suite", "finance", "Optional accounting system handoff planning."),
      integration("warehouse-device", "Warehouse device", "operations", "Optional scanner or device integration planning."),
    ],
    complianceAndAuditConcerns: [
      "Use audit and segregation-of-duties checklists for sensitive financial flows.",
      "Do not claim tax, payroll, or accounting compliance without expert review.",
    ],
    dataModelPatterns: ["transaction ledger", "stock movement log", "approval trail", "period close markers"],
    uiPatterns: ["role dashboards", "batch review tables", "drill-down reports", "approval queues"],
    deploymentNotes: ["Plan backup, reconciliation, and restore procedures before production use."],
    riskNotes: ["ERP scope can expand quickly; phase modules and require stakeholder signoff."],
    assumptions: ["Catalog metadata is starter guidance and does not replace accounting or operations expertise."],
    tags: ["enterprise", "finance", "operations"],
  },
  {
    familyId: "crm",
    name: "CRM",
    aliases: ["customer relationship management", "sales pipeline"],
    purpose:
      "Plan customer relationship systems for accounts, leads, opportunities, pipeline work, tickets, campaigns, and reporting.",
    typicalActors: ["sales representative", "sales manager", "support agent", "marketing user"],
    coreModules: [
      item("contacts", "Contacts", "People and organization relationship records."),
      item("leads", "Leads", "Potential customer qualification planning."),
      item("opportunities", "Opportunities", "Sales deal tracking."),
      item("pipeline", "Pipeline", "Stage-based sales process views."),
      item("tickets", "Tickets", "Support or service cases."),
      item("campaigns", "Campaigns", "Marketing outreach planning."),
    ],
    commonEntities: [
      item("contact", "Contact", "Person associated with a customer or lead."),
      item("account", "Account", "Organization or customer grouping."),
      item("lead", "Lead", "Potential customer before qualification."),
      item("opportunity", "Opportunity", "Potential sale or contract."),
      item("ticket", "Ticket", "Support request or issue."),
    ],
    workflows: [
      workflow(
        "lead-to-opportunity",
        "Lead to opportunity",
        "A lead is qualified and converted into a tracked sales opportunity.",
        ["sales representative", "sales manager"],
        ["Capture lead", "Qualify fit", "Convert opportunity", "Assign stage", "Review next action"],
      ),
    ],
    permissions: [
      item("contact-read", "Contact read", "View assigned customer information."),
      item("pipeline-manage", "Pipeline manage", "Update opportunities and stages."),
      item("campaign-review", "Campaign review", "Review outreach lists and campaign performance."),
    ],
    reports: [
      item("pipeline-forecast", "Pipeline forecast", "Sales value by stage and expected close period."),
      item("ticket-aging", "Ticket aging", "Open support requests by age and owner."),
    ],
    integrations: [
      integration("email-platform", "Email platform", "communication", "Optional email activity planning."),
      integration("calendar-system", "Calendar system", "scheduling", "Optional meeting sync planning."),
    ],
    complianceAndAuditConcerns: [
      "Review consent, retention, and access rules for customer data.",
      "Use privacy checklist language for marketing and communication workflows.",
    ],
    dataModelPatterns: ["account hierarchy", "activity timeline", "pipeline stages", "ownership assignment"],
    uiPatterns: ["kanban pipeline", "contact timeline", "ticket queue", "campaign dashboard"],
    deploymentNotes: ["Plan import hygiene and duplicate handling before rollout."],
    riskNotes: ["Customer data can include sensitive information and needs access review."],
    assumptions: ["Sales stages and qualification rules are organization-specific."],
    tags: ["sales", "support", "customers"],
  },
  {
    familyId: "pos",
    name: "POS",
    aliases: ["point of sale", "retail checkout"],
    purpose:
      "Plan point-of-sale systems for checkout, products, stock, discounts, billing, payments, returns, and cash closing.",
    typicalActors: ["cashier", "store manager", "inventory user", "auditor"],
    coreModules: [
      item("checkout", "Checkout", "Cart and sale completion planning."),
      item("products", "Products", "Sellable item catalog planning."),
      item("stock", "Stock", "Store inventory visibility."),
      item("discounts", "Discounts", "Promotions and manual adjustment rules."),
      item("billing", "Billing", "Receipts and invoice handoff planning."),
      item("payments", "Payments", "Payment method tracking and reconciliation planning."),
      item("returns", "Returns", "Refund and exchange workflows."),
      item("cash-closing", "Cash closing", "Cash drawer review and closing reports."),
    ],
    commonEntities: [
      item("sale", "Sale", "Completed checkout transaction."),
      item("product", "Product", "Sellable item."),
      item("price", "Price", "Current or promotional price."),
      item("payment", "Payment", "Payment record or method summary."),
      item("cash-session", "Cash session", "Cash drawer operating period."),
    ],
    workflows: [
      workflow(
        "checkout-sale",
        "Checkout sale",
        "A cashier scans items, applies allowed adjustments, records payment, and closes the sale.",
        ["cashier", "store manager"],
        ["Start cart", "Add products", "Apply permitted discounts", "Record payment", "Issue receipt"],
        ["Payment and tax handling require jurisdiction-specific review."],
      ),
    ],
    permissions: [
      item("checkout-operate", "Checkout operate", "Run normal sales."),
      item("discount-override", "Discount override", "Approve manual discounts."),
      item("cash-close", "Cash close", "Perform drawer closing review."),
    ],
    reports: [
      item("daily-sales", "Daily sales", "Sales totals by cashier, register, and payment method."),
      item("cash-variance", "Cash variance", "Expected versus counted cash summary."),
    ],
    integrations: [
      integration("payment-terminal", "Payment terminal", "payment", "Optional card terminal planning without live processing."),
      integration("receipt-printer", "Receipt printer", "device", "Optional local device planning."),
    ],
    complianceAndAuditConcerns: [
      "Use payment security and tax checklist guidance; do not claim payment compliance.",
      "Track overrides and returns for management review.",
    ],
    dataModelPatterns: ["immutable sale record", "cash session", "stock decrement event", "return reference"],
    uiPatterns: ["fast checkout screen", "large touch targets", "manager override dialog", "closing summary"],
    deploymentNotes: ["Plan offline tolerance, device setup, and reconciliation before store rollout."],
    riskNotes: ["POS affects money and inventory; require reconciliation and approval boundaries."],
    assumptions: ["Payment processing and tax rules need separate expert review."],
    tags: ["retail", "checkout", "payments"],
  },
  {
    familyId: "bi",
    name: "BI",
    aliases: ["business intelligence", "analytics", "reporting"],
    purpose:
      "Plan business intelligence systems for KPIs, dashboards, ETL planning, metrics, dimensions, and access-controlled reporting.",
    typicalActors: ["analyst", "manager", "executive", "data steward"],
    coreModules: [
      item("kpis", "KPIs", "Key performance indicator definitions."),
      item("dashboards", "Dashboards", "Role-based analytical views."),
      item("etl", "ETL planning", "Data movement and transformation planning."),
      item("metrics", "Metrics", "Reusable measure definitions."),
      item("dimensions", "Dimensions", "Analysis axes such as time, product, or region."),
      item("access-control", "Access control", "Report and dataset permission planning."),
    ],
    commonEntities: [
      item("metric", "Metric", "Defined measure with calculation guidance."),
      item("dimension", "Dimension", "Categorical or temporal analysis axis."),
      item("dataset", "Dataset", "Curated data collection for reporting."),
      item("dashboard", "Dashboard", "Grouped visualization surface."),
    ],
    workflows: [
      workflow(
        "dashboard-review",
        "Dashboard review",
        "A stakeholder reviews KPI definitions before dashboard publication.",
        ["analyst", "manager", "data steward"],
        ["Draft KPI", "Map source data", "Review definition", "Publish dashboard plan"],
        ["Incorrect metrics can drive bad decisions; require definition review."],
      ),
    ],
    permissions: [
      item("dashboard-view", "Dashboard view", "View assigned dashboards."),
      item("metric-author", "Metric author", "Draft and update KPI definitions."),
      item("dataset-admin", "Dataset admin", "Manage dataset access planning."),
    ],
    reports: [
      item("executive-scorecard", "Executive scorecard", "High-level KPI dashboard."),
      item("data-quality-summary", "Data quality summary", "Source freshness and quality signals."),
    ],
    integrations: [
      integration("warehouse", "Data warehouse", "data", "Optional analytical storage planning."),
      integration("bi-tool", "BI tool", "analytics", "Optional dashboard platform planning."),
    ],
    complianceAndAuditConcerns: [
      "Review data classification and row-level access before implementation.",
      "Document KPI assumptions and source lineage for auditability.",
    ],
    dataModelPatterns: ["star schema planning", "metric catalog", "semantic layer", "data lineage notes"],
    uiPatterns: ["dashboard grid", "filter panels", "drill-down charts", "export review"],
    deploymentNotes: ["Plan refresh cadence, ownership, and data quality checks."],
    riskNotes: ["BI outputs may expose sensitive aggregates or misleading metrics."],
    assumptions: ["Source systems and data quality need discovery before implementation."],
    tags: ["analytics", "reporting", "data"],
  },
  {
    familyId: "bpm",
    name: "BPM",
    aliases: ["business process management", "workflow management"],
    purpose:
      "Plan process-centric systems for states, approvals, rules, SLA tracking, exceptions, and operational visibility.",
    typicalActors: ["process owner", "operator", "approver", "auditor"],
    coreModules: [
      item("processes", "Processes", "Defined business process families."),
      item("states", "States", "Lifecycle states and transitions."),
      item("approvals", "Approvals", "Human review checkpoints."),
      item("rules", "Rules", "Business conditions and routing guidance."),
      item("sla", "SLA", "Service timing and escalation planning."),
      item("exceptions", "Exceptions", "Exception handling and recovery paths."),
    ],
    commonEntities: [
      item("process-instance", "Process instance", "Single running or planned process case."),
      item("state", "State", "Named lifecycle state."),
      item("transition", "Transition", "Allowed movement between states."),
      item("approval", "Approval", "Human review point in the process."),
    ],
    workflows: [
      workflow(
        "case-lifecycle",
        "Case lifecycle",
        "A case moves through states with rule checks and human approvals where required.",
        ["operator", "approver", "process owner"],
        ["Create case", "Assign owner", "Evaluate rule", "Request approval", "Close or escalate"],
        ["Catalog describes process planning only; it does not execute workflow automation."],
      ),
    ],
    permissions: [
      item("case-view", "Case view", "View process cases."),
      item("case-transition", "Case transition", "Move allowed cases between states."),
      item("process-admin", "Process admin", "Manage process definitions after review."),
    ],
    reports: [
      item("sla-breach-risk", "SLA breach risk", "Cases near timing thresholds."),
      item("process-throughput", "Process throughput", "Volume by process and state."),
    ],
    integrations: [
      integration("notification-channel", "Notification channel", "communication", "Optional reminder planning without delivery behavior."),
    ],
    complianceAndAuditConcerns: [
      "Review approval authority and audit trails for regulated processes.",
      "Keep process outputs advisory until explicit runtime approval exists.",
    ],
    dataModelPatterns: ["state machine", "transition history", "approval checkpoint", "exception log"],
    uiPatterns: ["state board", "approval queue", "case detail", "SLA indicators"],
    deploymentNotes: ["Plan process ownership and change control before rollout."],
    riskNotes: ["Process definitions can become operational controls and need review before execution."],
    assumptions: ["This catalog does not connect to native automation execution."],
    tags: ["workflow", "process", "approvals"],
  },
  {
    familyId: "cms",
    name: "CMS",
    aliases: ["content management system", "publishing platform"],
    purpose:
      "Plan content management systems for content, media, roles, publishing workflows, versioning, and review.",
    typicalActors: ["editor", "author", "publisher", "content administrator"],
    coreModules: [
      item("content", "Content", "Pages, articles, and structured content planning."),
      item("media", "Media", "Asset organization and usage planning."),
      item("roles", "Roles", "Editorial permissions and review responsibilities."),
      item("publishing", "Publishing workflows", "Draft, review, approval, and publication planning."),
      item("versioning", "Versioning", "Content history and rollback planning."),
    ],
    commonEntities: [
      item("content-item", "Content item", "Managed page, article, or block."),
      item("media-asset", "Media asset", "Image, document, or embedded asset."),
      item("revision", "Revision", "Saved content version."),
      item("taxonomy", "Taxonomy", "Category or tag grouping."),
    ],
    workflows: [
      workflow(
        "draft-to-publish",
        "Draft to publish",
        "An author drafts content and an editor reviews it before publication.",
        ["author", "editor", "publisher"],
        ["Create draft", "Review content", "Approve publication", "Publish", "Track revision"],
      ),
    ],
    permissions: [
      item("content-author", "Content author", "Create and edit drafts."),
      item("content-publish", "Content publish", "Approve and publish content."),
      item("media-manage", "Media manage", "Manage asset metadata."),
    ],
    reports: [
      item("content-inventory", "Content inventory", "Content status by owner, type, and publication state."),
    ],
    integrations: [
      integration("search-index", "Search index", "search", "Optional search indexing planning."),
      integration("cdn", "CDN", "delivery", "Optional delivery platform planning."),
    ],
    complianceAndAuditConcerns: [
      "Review content ownership, copyright, privacy, and retention checklists.",
    ],
    dataModelPatterns: ["content type", "revision history", "taxonomy tree", "publication state"],
    uiPatterns: ["editor workspace", "media browser", "publication calendar", "revision comparison"],
    deploymentNotes: ["Plan content migration, permissions, and preview environments."],
    riskNotes: ["Publishing workflows need editorial governance and rollback planning."],
    assumptions: ["Content models vary significantly by organization."],
    tags: ["content", "publishing", "media"],
  },
  {
    familyId: "hrms",
    name: "HRMS / HRIS",
    aliases: ["human resources management system", "human resources information system", "hris"],
    purpose:
      "Plan HR systems for employees, payroll handoff, attendance, leave, documents, and workforce reporting.",
    typicalActors: ["HR administrator", "employee", "manager", "payroll user"],
    coreModules: [
      item("employees", "Employees", "Worker profile and lifecycle planning."),
      item("payroll-hooks", "Payroll hooks", "Payroll handoff planning without payroll processing claims."),
      item("attendance", "Attendance", "Attendance and timesheet planning."),
      item("leave", "Leave", "Vacation, absence, and approval workflows."),
      item("documents", "Documents", "Employee document organization."),
    ],
    commonEntities: [
      item("employee", "Employee", "Worker or contractor record."),
      item("department", "Department", "Organizational unit."),
      item("leave-request", "Leave request", "Absence request and review state."),
      item("timesheet", "Timesheet", "Time entry or attendance summary."),
      item("employee-document", "Employee document", "HR-managed document metadata."),
    ],
    workflows: [
      workflow(
        "leave-request-review",
        "Leave request review",
        "An employee requests leave and a manager reviews it against policy guidance.",
        ["employee", "manager", "HR administrator"],
        ["Submit request", "Check balance guidance", "Review manager decision", "Record result"],
        ["Labor rules and payroll impacts need expert review."],
      ),
    ],
    permissions: [
      item("employee-self-view", "Employee self view", "View own HR information."),
      item("manager-review", "Manager review", "Review team requests."),
      item("hr-admin", "HR admin", "Manage HR records after policy review."),
    ],
    reports: [
      item("leave-balance-summary", "Leave balance summary", "Planned leave balances by employee or team."),
      item("headcount-summary", "Headcount summary", "Employee counts by department and status."),
    ],
    integrations: [
      integration("payroll-system", "Payroll system", "payroll", "Optional payroll handoff planning."),
      integration("identity-directory", "Identity directory", "identity", "Optional employee identity planning."),
    ],
    complianceAndAuditConcerns: [
      "Use privacy, labor policy, and retention checklists; do not claim legal compliance.",
      "Restrict sensitive employee data by role.",
    ],
    dataModelPatterns: ["employee profile", "organizational hierarchy", "request workflow", "document retention"],
    uiPatterns: ["employee self-service", "manager approval queue", "HR admin forms", "document vault"],
    deploymentNotes: ["Plan migration and privacy review before HR data import."],
    riskNotes: ["HR data is sensitive and requires strict access review."],
    assumptions: ["Payroll, labor, and benefits rules are jurisdiction-specific."],
    tags: ["hr", "people", "privacy"],
  },
  {
    familyId: "scm",
    name: "SCM",
    aliases: ["supply chain management", "procurement logistics"],
    purpose:
      "Plan supply chain systems for suppliers, procurement, logistics, warehouse coordination, and demand planning.",
    typicalActors: ["procurement user", "supplier manager", "warehouse user", "logistics coordinator"],
    coreModules: [
      item("suppliers", "Suppliers", "Supplier profiles, status, and review planning."),
      item("procurement", "Procurement", "Purchasing requests and sourcing planning."),
      item("logistics", "Logistics", "Shipment and transport coordination."),
      item("warehouse", "Warehouse", "Stock location and handling planning."),
      item("demand-planning", "Demand planning", "Forecast and replenishment planning."),
    ],
    commonEntities: [
      item("supplier", "Supplier", "Vendor or partner organization."),
      item("purchase-request", "Purchase request", "Internal procurement need."),
      item("shipment", "Shipment", "Transport or delivery event."),
      item("warehouse", "Warehouse", "Storage location."),
      item("demand-plan", "Demand plan", "Forecast guidance for supply planning."),
    ],
    workflows: [
      workflow(
        "supplier-to-receipt",
        "Supplier to receipt",
        "Procurement coordinates supplier order, logistics, receipt, and exception review.",
        ["procurement user", "logistics coordinator", "warehouse user"],
        ["Select supplier", "Plan order", "Track shipment", "Receive goods", "Review exception"],
      ),
    ],
    permissions: [
      item("supplier-manage", "Supplier manage", "Manage supplier planning records."),
      item("shipment-track", "Shipment track", "View logistics progress."),
      item("warehouse-receive", "Warehouse receive", "Record receipt planning events."),
    ],
    reports: [
      item("supplier-performance", "Supplier performance", "Supplier delivery and quality summary."),
      item("shipment-status", "Shipment status", "Open shipment status by lane or warehouse."),
    ],
    integrations: [
      integration("carrier-system", "Carrier system", "logistics", "Optional carrier status planning."),
      integration("supplier-portal", "Supplier portal", "partner", "Optional supplier collaboration planning."),
    ],
    complianceAndAuditConcerns: [
      "Review vendor due diligence, customs, and traceability checklists where relevant.",
    ],
    dataModelPatterns: ["supplier master", "shipment event timeline", "procurement request", "warehouse receipt"],
    uiPatterns: ["supplier dashboard", "shipment board", "exception queue", "forecast review"],
    deploymentNotes: ["Plan partner onboarding and data ownership before integration."],
    riskNotes: ["Supply chain processes cross organizations and need clear ownership boundaries."],
    assumptions: ["Supplier, logistics, and customs details depend on geography and industry."],
    tags: ["supply-chain", "procurement", "logistics"],
  },
  {
    familyId: "lms",
    name: "LMS",
    aliases: ["learning management system", "training platform"],
    purpose:
      "Plan learning systems for courses, learners, instructors, assessments, progress tracking, and reporting.",
    typicalActors: ["learner", "instructor", "training administrator", "manager"],
    coreModules: [
      item("courses", "Courses", "Course catalog and structure planning."),
      item("learners", "Learners", "Enrollment and progress planning."),
      item("instructors", "Instructors", "Instructor assignment and review surfaces."),
      item("assessments", "Assessments", "Quiz, exam, or assignment planning."),
      item("progress", "Progress", "Completion and learning path tracking."),
    ],
    commonEntities: [
      item("course", "Course", "Learning unit or curriculum."),
      item("lesson", "Lesson", "Course content segment."),
      item("enrollment", "Enrollment", "Learner assignment to a course."),
      item("assessment", "Assessment", "Evaluation activity."),
      item("completion", "Completion", "Progress milestone."),
    ],
    workflows: [
      workflow(
        "course-completion",
        "Course completion",
        "A learner enrolls, completes content, submits assessment, and receives completion status.",
        ["learner", "instructor", "training administrator"],
        ["Enroll learner", "Complete lesson", "Submit assessment", "Review result", "Record completion"],
      ),
    ],
    permissions: [
      item("course-view", "Course view", "Access assigned learning content."),
      item("course-author", "Course author", "Manage course planning content."),
      item("progress-review", "Progress review", "Review learner progress by role."),
    ],
    reports: [
      item("completion-report", "Completion report", "Training completion by course, learner, or team."),
    ],
    integrations: [
      integration("identity-directory", "Identity directory", "identity", "Optional learner identity planning."),
      integration("content-library", "Content library", "content", "Optional content source planning."),
    ],
    complianceAndAuditConcerns: [
      "Review training evidence, retention, and learner privacy checklists.",
    ],
    dataModelPatterns: ["course hierarchy", "enrollment record", "assessment attempt", "completion certificate metadata"],
    uiPatterns: ["learner portal", "course builder", "progress dashboard", "assessment review"],
    deploymentNotes: ["Plan content migration and role-based visibility before rollout."],
    riskNotes: ["Training records can become compliance evidence and need careful retention rules."],
    assumptions: ["Certification or regulated training requirements need expert review."],
    tags: ["learning", "training", "education"],
  },
  {
    familyId: "ecommerce",
    name: "E-commerce",
    aliases: ["online store", "commerce platform"],
    purpose:
      "Plan commerce systems for catalog, cart, checkout, orders, payments, fulfillment, returns, and customer reporting.",
    typicalActors: ["customer", "store administrator", "fulfillment user", "support agent"],
    coreModules: [
      item("catalog", "Catalog", "Product browsing and merchandising planning."),
      item("cart", "Cart", "Shopping cart planning."),
      item("checkout", "Checkout", "Order placement and review planning."),
      item("orders", "Orders", "Order lifecycle tracking."),
      item("payments", "Payments", "Payment handoff and reconciliation planning."),
      item("fulfillment", "Fulfillment", "Packing, shipping, and delivery planning."),
    ],
    commonEntities: [
      item("product", "Product", "Sellable item or service."),
      item("customer", "Customer", "Buyer account or guest profile."),
      item("cart", "Cart", "Pending purchase selection."),
      item("order", "Order", "Submitted purchase."),
      item("shipment", "Shipment", "Fulfillment tracking record."),
    ],
    workflows: [
      workflow(
        "cart-to-fulfillment",
        "Cart to fulfillment",
        "A customer places an order and fulfillment prepares shipment after reviewable payment status.",
        ["customer", "fulfillment user", "support agent"],
        ["Add item", "Review cart", "Place order", "Prepare fulfillment", "Track delivery"],
        ["Payment and consumer protection rules require separate review."],
      ),
    ],
    permissions: [
      item("catalog-admin", "Catalog admin", "Manage product planning data."),
      item("order-manage", "Order manage", "Review and update order status."),
      item("support-view", "Support view", "View customer order context for support."),
    ],
    reports: [
      item("sales-funnel", "Sales funnel", "Cart, checkout, and order conversion summary."),
      item("fulfillment-backlog", "Fulfillment backlog", "Open orders by status and age."),
    ],
    integrations: [
      integration("payment-gateway", "Payment gateway", "payment", "Optional payment handoff planning without live payment behavior."),
      integration("shipping-provider", "Shipping provider", "shipping", "Optional fulfillment integration planning."),
    ],
    complianceAndAuditConcerns: [
      "Use privacy, payment, tax, and consumer rights checklists; do not claim compliance.",
    ],
    dataModelPatterns: ["product catalog", "order lifecycle", "payment status", "shipment tracking"],
    uiPatterns: ["product grid", "cart drawer", "checkout flow", "order management table"],
    deploymentNotes: ["Plan performance, rollback, and payment sandboxing before implementation."],
    riskNotes: ["Commerce affects customers, money, and inventory; require review gates."],
    assumptions: ["Tax, payment, shipping, and refund rules are market-specific."],
    tags: ["commerce", "orders", "customers"],
  },
  {
    familyId: "inventory",
    name: "Inventory",
    aliases: ["stock management", "warehouse inventory"],
    purpose:
      "Plan inventory systems for stock balances, movements, warehouses, adjustments, counts, and reconciliation.",
    typicalActors: ["warehouse user", "inventory manager", "auditor", "purchasing user"],
    coreModules: [
      item("stock", "Stock", "Stock balance planning."),
      item("movements", "Movements", "Inbound, outbound, transfer, and adjustment events."),
      item("warehouses", "Warehouses", "Location and bin planning."),
      item("adjustments", "Adjustments", "Reviewed stock correction workflows."),
      item("reconciliation", "Reconciliation", "Cycle count and variance review planning."),
    ],
    commonEntities: [
      item("sku", "SKU", "Stock keeping unit."),
      item("stock-balance", "Stock balance", "Quantity by item and location."),
      item("stock-movement", "Stock movement", "Traceable inventory event."),
      item("warehouse", "Warehouse", "Storage location."),
      item("count-session", "Count session", "Inventory counting event."),
    ],
    workflows: [
      workflow(
        "cycle-count",
        "Cycle count",
        "Warehouse staff count stock and a manager reviews variances before adjustment.",
        ["warehouse user", "inventory manager", "auditor"],
        ["Select items", "Count quantity", "Compare expected balance", "Review variance", "Record adjustment plan"],
      ),
    ],
    permissions: [
      item("stock-view", "Stock view", "View inventory balances."),
      item("movement-record", "Movement record", "Record inventory movement planning events."),
      item("adjustment-approve", "Adjustment approve", "Review adjustment requests."),
    ],
    reports: [
      item("stock-on-hand", "Stock on hand", "Current quantity by item and location."),
      item("variance-report", "Variance report", "Inventory count variance summary."),
    ],
    integrations: [
      integration("barcode-scanner", "Barcode scanner", "device", "Optional device planning."),
      integration("erp-inventory", "ERP inventory", "erp", "Optional ERP handoff planning."),
    ],
    complianceAndAuditConcerns: [
      "Review traceability and approval checklists for adjustments and shrinkage.",
    ],
    dataModelPatterns: ["movement ledger", "location hierarchy", "lot or serial tracking", "count variance"],
    uiPatterns: ["stock table", "movement form", "count worksheet", "variance review"],
    deploymentNotes: ["Plan initial stock import and physical count before launch."],
    riskNotes: ["Inventory errors can affect financial and fulfillment operations."],
    assumptions: ["Lot, serial, and expiration tracking depend on product domain."],
    tags: ["stock", "warehouse", "operations"],
  },
  {
    familyId: "accounting-billing",
    name: "Accounting / billing",
    aliases: ["accounting", "billing", "invoicing"],
    purpose:
      "Plan accounting and billing systems for invoices, ledgers, taxes, payments, audit trails, and reconciliation guidance.",
    typicalActors: ["accountant", "billing clerk", "finance manager", "auditor"],
    coreModules: [
      item("invoices", "Invoices", "Invoice creation and status planning."),
      item("ledgers", "Ledgers", "Financial event organization planning."),
      item("taxes", "Taxes", "Tax field and review planning without legal claims."),
      item("payments", "Payments", "Payment application and reconciliation planning."),
      item("audit-trails", "Audit trails", "Traceability for sensitive financial records."),
    ],
    commonEntities: [
      item("invoice", "Invoice", "Billing document or receivable."),
      item("payment", "Payment", "Payment record or settlement marker."),
      item("ledger-entry", "Ledger entry", "Financial event planning object."),
      item("customer", "Customer", "Bill-to party."),
      item("tax-rule", "Tax rule", "Reviewed tax guidance placeholder."),
    ],
    workflows: [
      workflow(
        "invoice-to-payment",
        "Invoice to payment",
        "A finance user issues an invoice, records payment status, and reviews reconciliation.",
        ["billing clerk", "accountant", "finance manager"],
        ["Prepare invoice", "Review charges", "Issue invoice", "Record payment", "Reconcile balance"],
        ["Tax and accounting treatment require expert review."],
      ),
    ],
    permissions: [
      item("invoice-create", "Invoice create", "Prepare invoices."),
      item("payment-apply", "Payment apply", "Record payment application planning events."),
      item("finance-audit-read", "Finance audit read", "Review financial traceability."),
    ],
    reports: [
      item("accounts-receivable-aging", "Accounts receivable aging", "Outstanding invoices by age."),
      item("payment-reconciliation", "Payment reconciliation", "Payments matched against invoices."),
    ],
    integrations: [
      integration("accounting-platform", "Accounting platform", "finance", "Optional accounting platform handoff planning."),
      integration("tax-service", "Tax service", "tax", "Optional tax calculation planning without live calls."),
    ],
    complianceAndAuditConcerns: [
      "Use accounting, tax, and audit checklist guidance only; do not claim legal or accounting compliance.",
      "Require human review for financial posting and close processes.",
    ],
    dataModelPatterns: ["invoice lifecycle", "payment allocation", "ledger event", "audit trail"],
    uiPatterns: ["invoice editor", "aging dashboard", "payment matching table", "audit view"],
    deploymentNotes: ["Plan reconciliation, backups, and period-close review before production use."],
    riskNotes: ["Accounting errors can create legal and financial exposure."],
    assumptions: ["Accounting policy and tax treatment are expert-owned."],
    tags: ["finance", "billing", "audit"],
  },
  {
    familyId: "document-management",
    name: "Document management",
    aliases: ["document control", "records management"],
    purpose:
      "Plan document management systems for documents, folders, retention, approvals, search, and access control.",
    typicalActors: ["document owner", "reviewer", "records manager", "auditor"],
    coreModules: [
      item("documents", "Documents", "Document metadata and lifecycle planning."),
      item("folders", "Folders", "Organization and access grouping."),
      item("retention", "Retention", "Retention schedule guidance."),
      item("approvals", "Approvals", "Review and signoff planning."),
      item("search", "Search", "Discovery and filtering planning."),
    ],
    commonEntities: [
      item("document", "Document", "Managed document metadata."),
      item("folder", "Folder", "Organizational container."),
      item("version", "Version", "Document revision."),
      item("review", "Review", "Approval or feedback event."),
      item("retention-rule", "Retention rule", "Policy guidance placeholder."),
    ],
    workflows: [
      workflow(
        "document-review",
        "Document review",
        "A document owner submits a version for review and records approval status.",
        ["document owner", "reviewer", "records manager"],
        ["Upload metadata", "Assign review", "Collect feedback", "Approve version", "Apply retention guidance"],
      ),
    ],
    permissions: [
      item("document-read", "Document read", "View documents in allowed scopes."),
      item("document-submit", "Document submit", "Submit a new version for review."),
      item("records-admin", "Records admin", "Manage retention guidance and access planning."),
    ],
    reports: [
      item("review-backlog", "Review backlog", "Documents waiting for review."),
      item("retention-summary", "Retention summary", "Documents by retention category and age."),
    ],
    integrations: [
      integration("object-storage", "Object storage", "storage", "Optional storage planning."),
      integration("search-engine", "Search engine", "search", "Optional indexing planning."),
    ],
    complianceAndAuditConcerns: [
      "Review retention, privacy, legal hold, and access checklists before implementation.",
    ],
    dataModelPatterns: ["document metadata", "version chain", "access policy", "retention schedule"],
    uiPatterns: ["document browser", "metadata form", "review queue", "search results"],
    deploymentNotes: ["Plan storage, backup, restore, and migration approach before production use."],
    riskNotes: ["Documents can contain sensitive data and require careful access and retention controls."],
    assumptions: ["Legal hold and retention rules are organization-specific."],
    tags: ["documents", "records", "search"],
  },
  {
    familyId: "project-management",
    name: "Project management systems",
    aliases: ["project management", "task management", "work management"],
    purpose:
      "Plan project management systems for projects, tasks, teams, timelines, risks, reports, and delivery coordination.",
    typicalActors: ["project manager", "team member", "stakeholder", "portfolio manager"],
    coreModules: [
      item("projects", "Projects", "Project scope and lifecycle planning."),
      item("tasks", "Tasks", "Work item tracking."),
      item("teams", "Teams", "Assignment and responsibility planning."),
      item("timelines", "Timelines", "Milestones and schedule planning."),
      item("risks", "Risks", "Risk register and mitigation planning."),
      item("reports", "Reports", "Status and portfolio reporting."),
    ],
    commonEntities: [
      item("project", "Project", "Delivery initiative."),
      item("task", "Task", "Unit of work."),
      item("milestone", "Milestone", "Key delivery marker."),
      item("risk", "Risk", "Potential issue or uncertainty."),
      item("team-member", "Team member", "Assigned participant."),
    ],
    workflows: [
      workflow(
        "task-delivery",
        "Task delivery",
        "A project manager creates work, assigns ownership, tracks status, and reviews completion.",
        ["project manager", "team member", "stakeholder"],
        ["Create task", "Assign owner", "Update status", "Review blocker", "Close work"],
      ),
    ],
    permissions: [
      item("task-update", "Task update", "Update assigned work."),
      item("project-manage", "Project manage", "Manage project planning records."),
      item("portfolio-view", "Portfolio view", "View cross-project summaries."),
    ],
    reports: [
      item("status-report", "Status report", "Project progress, risks, and upcoming milestones."),
      item("portfolio-summary", "Portfolio summary", "Projects grouped by status and priority."),
    ],
    integrations: [
      integration("calendar", "Calendar", "scheduling", "Optional calendar planning."),
      integration("source-control", "Source control", "engineering", "Optional engineering activity planning."),
    ],
    complianceAndAuditConcerns: [
      "Review access, retention, and stakeholder visibility for sensitive projects.",
    ],
    dataModelPatterns: ["work breakdown", "status lifecycle", "dependency graph", "risk register"],
    uiPatterns: ["kanban board", "timeline", "task detail", "portfolio dashboard"],
    deploymentNotes: ["Plan notification policy and migration from existing trackers before rollout."],
    riskNotes: ["Project tooling can become noisy if workflows are too rigid or too broad."],
    assumptions: ["Project methodology and reporting cadence vary by organization."],
    tags: ["projects", "tasks", "planning"],
  },
];

export const listBusinessSystemFamilies = (): readonly BusinessSystemFamily[] =>
  businessSystemsCatalog;

export const getBusinessSystemFamily = (
  familyId: BusinessSystemFamilyId,
): BusinessSystemFamily | undefined =>
  businessSystemsCatalog.find((family) => family.familyId === familyId);
