// src/scaffold/templates/astro.ts

import type { StackTemplate } from "../templates.js";

export const astroTemplate: StackTemplate = {
  "package.json": JSON.stringify({
    name: "site",
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "astro dev",
      build: "astro build",
      preview: "astro preview",
    },
    dependencies: {
      astro: "^5.0.0",
    },
    devDependencies: {
      typescript: "^5.0.0",
      "@types/node": "^20.0.0",
    },
  }, null, 2),

  "tsconfig.json": JSON.stringify({
    extends: "astro/tsconfigs/strict",
  }, null, 2),

  "astro.config.mjs": `import { defineConfig } from "astro/config";

export default defineConfig({
  site: "https://example.com",
  output: "static",
});
`,

  "src/layouts/Base.astro": `---
interface Props {
  title: string;
}
const { title } = Astro.props;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
  </head>
  <body>
    <slot />
  </body>
</html>
`,

  "src/pages/index.astro": `---
import Base from "../layouts/Base.astro";
---

<Base title="Home">
  <main>
    <h1>Welcome</h1>
    <p>Generated by ORQUESTADOR-PRIME scaffold.</p>
  </main>
</Base>
`,

  "src/pages/404.astro": `---
import Base from "../layouts/Base.astro";
---

<Base title="Not Found">
  <main>
    <h1>404 — Not Found</h1>
    <a href="/">Go home</a>
  </main>
</Base>
`,
};
