// src/scaffold/templates/remix.ts

import type { StackTemplate } from "../templates.js";

export const remixTemplate: StackTemplate = {
  "package.json": JSON.stringify({
    name: "app",
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "remix vite:dev",
      build: "remix vite:build",
      start: "remix-serve ./build/server/index.js",
    },
    dependencies: {
      "@remix-run/node": "^2.0.0",
      "@remix-run/react": "^2.0.0",
      "@remix-run/serve": "^2.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      isbot: "^5.0.0",
    },
    devDependencies: {
      "@remix-run/dev": "^2.0.0",
      typescript: "^5.0.0",
      vite: "^6.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      "@types/node": "^20.0.0",
    },
  }, null, 2),

  "tsconfig.json": JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      lib: ["DOM", "DOM.Iterable", "ES2022"],
      module: "ESNext",
      moduleResolution: "bundler",
      strict: true,
      skipLibCheck: true,
      jsx: "react-jsx",
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      paths: { "~/*": ["./app/*"] },
    },
    include: ["app", "env.d.ts"],
    exclude: ["node_modules"],
  }, null, 2),

  "vite.config.ts": `import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [remix()],
  server: { port: 3000 },
});
`,

  "app/root.tsx": `import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        <Outlet />
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}
`,

  "app/routes/_index.tsx": `import type { MetaFunction } from "@remix-run/node";

export const meta: MetaFunction = () => [
  { title: "App" },
  { name: "description", content: "Generated by ORQUESTADOR-PRIME" },
];

export default function Index() {
  return (
    <main>
      <h1>Welcome</h1>
      <p>Generated by ORQUESTADOR-PRIME scaffold.</p>
    </main>
  );
}
`,

  "app/routes/api.health.tsx": `import { json } from "@remix-run/node";

export function loader() {
  return json({ status: "ok", timestamp: new Date().toISOString() });
}
`,
};
