// src/scaffold/templates/viteReact.ts

import type { StackTemplate } from "../templates.js";

export const viteReactTemplate: StackTemplate = {
  "package.json": JSON.stringify({
    name: "app",
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc && vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^19.0.0",
      "react-dom": "^19.0.0",
    },
    devDependencies: {
      typescript: "^5.0.0",
      vite: "^6.0.0",
      "@vitejs/plugin-react": "^4.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      "@types/node": "^20.0.0",
    },
  }, null, 2),

  "tsconfig.json": JSON.stringify({
    compilerOptions: {
      target: "ES2020",
      lib: ["ES2020", "DOM", "DOM.Iterable"],
      module: "ESNext",
      moduleResolution: "bundler",
      strict: true,
      skipLibCheck: true,
      jsx: "react-jsx",
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
    },
    include: ["src"],
    exclude: ["node_modules"],
  }, null, 2),

  "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { port: 3000 },
});
`,

  "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,

  "src/main.tsx": `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.js";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
`,

  "src/App.tsx": `export default function App() {
  return (
    <main>
      <h1>Welcome</h1>
      <p>Generated by ORQUESTADOR-PRIME scaffold.</p>
    </main>
  );
}
`,

  "src/types/index.ts": `export interface ApiResponse<T> {
  data: T;
  error?: string;
}
`,
};
