import type {
  InterviewExpectedAnswerType,
  InterviewQuestion,
  InterviewQuestionCategory,
  InterviewRiskLevel,
  StakeholderInterviewMode,
} from "./types.js";

export const STAKEHOLDER_INTERVIEW_MODES = [
  "ceo_business_owner",
  "operational_user",
  "technical_user",
  "auditor_compliance",
  "client_customer",
  "project_manager",
  "finance_admin",
  "support_helpdesk",
] as const satisfies readonly StakeholderInterviewMode[];

export const INTERVIEW_QUESTION_CATEGORIES = [
  "actors",
  "business_rules",
  "processes",
  "exceptions",
  "entities",
  "permissions",
  "integrations",
  "reports",
  "compliance",
  "volume_performance",
  "sla",
  "risks",
  "constraints",
  "data_migration",
  "ux_workflows",
  "deployment",
] as const satisfies readonly InterviewQuestionCategory[];

export const INTERVIEW_EXPECTED_ANSWER_TYPES = [
  "text",
  "number",
  "boolean",
  "enum",
  "list",
  "structured",
  "unknown",
] as const satisfies readonly InterviewExpectedAnswerType[];

const question = (
  questionId: string,
  mode: StakeholderInterviewMode,
  category: InterviewQuestionCategory,
  text: string,
  purpose: string,
  expectedAnswerType: InterviewExpectedAnswerType,
  required: boolean,
  followUps: string[],
  mapsTo: string[],
  riskLevel: InterviewRiskLevel,
  tags: string[],
): InterviewQuestion => ({
  questionId,
  mode,
  category,
  text,
  purpose,
  expectedAnswerType,
  required,
  followUps,
  mapsTo,
  riskLevel,
  tags,
});

export const interviewQuestionBank: readonly InterviewQuestion[] = [
  question(
    "ceo-goals-actors",
    "ceo_business_owner",
    "actors",
    "Which stakeholder groups must the system serve, and who owns final business decisions?",
    "Identify business ownership, key actors, and decision authority before blueprint enrichment.",
    "structured",
    true,
    ["Which groups are internal, external, or executive?", "Who approves changes to scope?"],
    ["actors", "permissions", "roadmap"],
    "high",
    ["strategy", "ownership"],
  ),
  question(
    "ceo-success-reports",
    "ceo_business_owner",
    "reports",
    "Which reports or metrics prove the system is successful after rollout?",
    "Capture executive success criteria and reporting expectations.",
    "list",
    true,
    ["Which metrics are reviewed weekly or monthly?", "Which decisions depend on these metrics?"],
    ["reports", "estimation", "roadmap"],
    "medium",
    ["kpi", "reporting"],
  ),
  question(
    "operations-processes",
    "operational_user",
    "processes",
    "What daily workflow should the system support from start to finish?",
    "Capture the real operational sequence before module assumptions are treated as complete.",
    "structured",
    true,
    ["Where does the workflow start?", "What marks it as complete?", "Who performs each handoff?"],
    ["workflows", "moduleBlueprintInputs"],
    "high",
    ["workflow", "operations"],
  ),
  question(
    "operations-exceptions",
    "operational_user",
    "exceptions",
    "What exceptions, rework, cancellations, or manual overrides happen in normal operations?",
    "Reveal edge cases that generic module blueprints usually miss.",
    "list",
    true,
    ["Which exceptions are most frequent?", "Who can approve an override?"],
    ["businessRules", "risks", "permissions"],
    "high",
    ["exceptions", "risk"],
  ),
  question(
    "technical-integrations",
    "technical_user",
    "integrations",
    "Which existing systems, devices, APIs, imports, or exports must be considered?",
    "Map integration surfaces without creating connectors or live calls.",
    "list",
    true,
    ["Which integrations are required on day one?", "Which can remain manual at first?"],
    ["integrations", "deployment", "risks"],
    "high",
    ["integration", "technical"],
  ),
  question(
    "technical-deployment",
    "technical_user",
    "deployment",
    "What deployment, hosting, identity, backup, and operational constraints are already known?",
    "Collect technical constraints for later architecture and roadmap planning.",
    "structured",
    true,
    ["Are there environment restrictions?", "Who operates backups and access control?"],
    ["deployment", "constraints", "estimation"],
    "medium",
    ["deployment", "operations"],
  ),
  question(
    "auditor-compliance",
    "auditor_compliance",
    "compliance",
    "Which policies, audit checks, retention rules, or review gates must be considered?",
    "Collect compliance checklist needs without making certification claims.",
    "structured",
    true,
    ["Which records need traceability?", "Which decisions require human review?"],
    ["auditConcerns", "permissions", "risks"],
    "high",
    ["audit", "governance"],
  ),
  question(
    "auditor-permissions",
    "auditor_compliance",
    "permissions",
    "Which roles must be separated to reduce fraud, privacy, or operational risk?",
    "Identify segregation-of-duties and access review needs.",
    "list",
    true,
    ["Which role combinations are not allowed?", "Who can review access changes?"],
    ["permissions", "businessRules", "auditConcerns"],
    "high",
    ["permissions", "controls"],
  ),
  question(
    "customer-ux",
    "client_customer",
    "ux_workflows",
    "What should customers or external users be able to complete without help?",
    "Capture external user expectations and self-service workflows.",
    "list",
    true,
    ["Which steps cause confusion today?", "Which notifications or confirmations matter?"],
    ["uiPatterns", "workflows", "reports"],
    "medium",
    ["customer", "ux"],
  ),
  question(
    "customer-sla",
    "client_customer",
    "sla",
    "What response times, service times, or status visibility do customers expect?",
    "Identify service expectations for later roadmap and risk planning.",
    "structured",
    false,
    ["What is acceptable during peak periods?", "What status updates reduce support requests?"],
    ["sla", "reports", "risks"],
    "medium",
    ["customer", "sla"],
  ),
  question(
    "pm-constraints",
    "project_manager",
    "constraints",
    "What budget, schedule, team, vendor, or rollout constraints are already fixed?",
    "Make delivery constraints explicit before estimating or planning implementation.",
    "structured",
    true,
    ["Which constraints are negotiable?", "Which dependencies can block rollout?"],
    ["roadmap", "risks", "estimation"],
    "high",
    ["delivery", "constraints"],
  ),
  question(
    "pm-risks",
    "project_manager",
    "risks",
    "What are the top project risks that could delay adoption or delivery?",
    "Capture project delivery risks and mitigation ownership.",
    "list",
    true,
    ["Who owns each mitigation?", "Which risks need an early spike or decision?"],
    ["risks", "roadmap", "assumptions"],
    "high",
    ["delivery", "risk"],
  ),
  question(
    "finance-rules",
    "finance_admin",
    "business_rules",
    "Which pricing, approval, billing, reconciliation, or closing rules affect this system?",
    "Identify finance and administrative rules that need expert review.",
    "structured",
    true,
    ["Which rules vary by branch, customer, or period?", "Who approves exceptions?"],
    ["businessRules", "permissions", "auditConcerns"],
    "high",
    ["finance", "rules"],
  ),
  question(
    "finance-migration",
    "finance_admin",
    "data_migration",
    "Which existing records must be migrated, reconciled, archived, or left read-only?",
    "Surface migration and reconciliation concerns before implementation planning.",
    "structured",
    true,
    ["Which data must be trusted at launch?", "Which data needs cleanup before migration?"],
    ["dataConsiderations", "risks", "estimation"],
    "high",
    ["migration", "finance"],
  ),
  question(
    "support-volume",
    "support_helpdesk",
    "volume_performance",
    "What user volumes, ticket volumes, peak periods, and common support issues should be expected?",
    "Collect operational scale and support load signals.",
    "structured",
    true,
    ["When do peaks happen?", "Which issues are most expensive to support?"],
    ["volume", "risks", "testConsiderations"],
    "medium",
    ["support", "volume"],
  ),
  question(
    "support-entities",
    "support_helpdesk",
    "entities",
    "Which records do support users need to inspect to diagnose common issues?",
    "Identify support-facing entities and privacy-sensitive access needs.",
    "list",
    true,
    ["Which fields should support never see?", "Which history is needed for diagnosis?"],
    ["entities", "permissions", "auditConcerns"],
    "medium",
    ["support", "entities"],
  ),
];

export const listInterviewQuestions = (): readonly InterviewQuestion[] =>
  interviewQuestionBank;

export const listInterviewQuestionsByMode = (
  mode: StakeholderInterviewMode,
): readonly InterviewQuestion[] =>
  interviewQuestionBank.filter((questionItem) => questionItem.mode === mode);

export const listInterviewQuestionsByCategory = (
  category: InterviewQuestionCategory,
): readonly InterviewQuestion[] =>
  interviewQuestionBank.filter((questionItem) => questionItem.category === category);
