import type { ToolCapability, ToolRegistryEntry } from "./types.js";

const ALL_CHANNELS: ToolRegistryEntry["allowedChannels"] = [
  "cli",
  "whatsapp",
  "omi",
  "dashboard",
  "openclaw",
  "system",
  "api",
];

const LOCAL_READ_CHANNELS: ToolRegistryEntry["allowedChannels"] = [
  "cli",
  "dashboard",
  "system",
];

const EXTERNAL_REQUEST_CHANNELS: ToolRegistryEntry["allowedChannels"] = [
  "whatsapp",
  "omi",
  "dashboard",
  "api",
];

export const TOOL_REGISTRY = [
  {
    toolId: "tool.registry.inspect",
    capability: "tool.registry.inspect",
    category: "tool-registry",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: ALL_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Read static tool and capability registry metadata.",
  },
  {
    toolId: "permission.check",
    capability: "permission.check",
    category: "permission",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: LOCAL_READ_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Evaluate a permission request without executing the requested capability.",
  },
  {
    toolId: "permission.audit.inspect",
    capability: "permission.audit.inspect",
    category: "permission",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: LOCAL_READ_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Read redacted permission audit summaries.",
  },
  {
    toolId: "action.proposal.create",
    capability: "action.proposal.create",
    category: "query",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: EXTERNAL_REQUEST_CHANNELS,
    requiredPermissions: ["action.proposal.create"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Create an action proposal through a guarded bridge.",
  },
  {
    toolId: "action.review.request",
    capability: "action.review.request",
    category: "query",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: EXTERNAL_REQUEST_CHANNELS,
    requiredPermissions: ["action.review.request"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Move an existing proposal into review through guarded policy.",
  },
  {
    toolId: "action.dispatch.approved",
    capability: "action.dispatch.approved",
    category: "tool-invoke",
    riskLevel: "review-required",
    mutatesRepo: true,
    networkAccess: false,
    externalService: null,
    requiresApproval: true,
    allowedChannels: ["cli", "dashboard"],
    requiredPermissions: ["action.dispatch.approved"],
    requiredEnv: ["ACTIONS_REAL_EXECUTION_ENABLED"],
    dryRunSupported: false,
    realExecutionSupported: true,
    forbiddenByDefault: true,
    description: "Dispatch an already approved proposal through existing execution gates.",
  },
  {
    toolId: "memory.v2.retrieve",
    capability: "memory.v2.retrieve",
    category: "memory",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: LOCAL_READ_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Retrieve project-scoped Memory V2 safe context.",
  },
  {
    toolId: "learning.export",
    capability: "learning.export",
    category: "learning",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: LOCAL_READ_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Export redacted learning datasets to stdout or explicit file path.",
  },
  {
    toolId: "supervisor.status",
    capability: "supervisor.status",
    category: "supervisor",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: LOCAL_READ_CHANNELS,
    requiredPermissions: [],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: false,
    description: "Build read-only supervisor advisory status.",
  },
  {
    toolId: "notification.inbox.create",
    capability: "notification.inbox.create",
    category: "notification",
    riskLevel: "safe",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard", "system"],
    requiredPermissions: ["notification.inbox.create"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Create a local redacted inbox notification.",
  },
  {
    toolId: "job.queue.enqueue",
    capability: "job.queue.enqueue",
    category: "job",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard", "system"],
    requiredPermissions: ["job.queue.enqueue"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Enqueue a local job record without starting a daemon.",
  },
  {
    toolId: "openclaw.tool_invoke.dry_run",
    capability: "openclaw.tool_invoke.dry_run",
    category: "tool-invoke",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: true,
    externalService: "openclaw",
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard", "openclaw"],
    requiredPermissions: ["openclaw.tool_invoke.dry_run"],
    requiredEnv: ["OPENCLAW_GATEWAY_TOKEN"],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Invoke OpenClaw tools in dry-run mode only.",
  },
  {
    toolId: "computer.action.dry_run",
    capability: "computer.action.dry_run",
    category: "computer-use",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: "openclaw",
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard"],
    requiredPermissions: ["computer.action.dry_run"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Plan a computer-use action without clicking, typing, or calling OpenClaw.",
  },
  {
    toolId: "repo.file_write.preview",
    capability: "repo.file_write.preview",
    category: "file-write",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard"],
    requiredPermissions: ["repo.file_write.preview"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Preview file-write changes without mutating files.",
  },
  {
    toolId: "repo.file_write.real",
    capability: "repo.file_write.real",
    category: "file-write",
    riskLevel: "review-required",
    mutatesRepo: true,
    networkAccess: false,
    externalService: null,
    requiresApproval: true,
    allowedChannels: ["cli"],
    requiredPermissions: ["repo.file_write.real"],
    requiredEnv: ["ACTIONS_REAL_EXECUTION_ENABLED"],
    dryRunSupported: false,
    realExecutionSupported: true,
    forbiddenByDefault: true,
    description: "Perform real file-write execution behind existing dual gates.",
  },
  {
    toolId: "repo.git_branch.preview",
    capability: "repo.git_branch.preview",
    category: "git-branch",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: false,
    externalService: null,
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard"],
    requiredPermissions: ["repo.git_branch.preview"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Preview git branch creation.",
  },
  {
    toolId: "repo.git_branch.real",
    capability: "repo.git_branch.real",
    category: "git-branch",
    riskLevel: "review-required",
    mutatesRepo: true,
    networkAccess: false,
    externalService: null,
    requiresApproval: true,
    allowedChannels: ["cli"],
    requiredPermissions: ["repo.git_branch.real"],
    requiredEnv: ["ACTIONS_REAL_EXECUTION_ENABLED"],
    dryRunSupported: false,
    realExecutionSupported: true,
    forbiddenByDefault: true,
    description: "Create a git branch behind existing real-execution gates.",
  },
  {
    toolId: "repo.pr_create.preview",
    capability: "repo.pr_create.preview",
    category: "pr-create",
    riskLevel: "review-required",
    mutatesRepo: false,
    networkAccess: true,
    externalService: "github",
    requiresApproval: false,
    allowedChannels: ["cli", "dashboard"],
    requiredPermissions: ["repo.pr_create.preview"],
    requiredEnv: [],
    dryRunSupported: true,
    realExecutionSupported: false,
    forbiddenByDefault: true,
    description: "Preview PR creation without creating or merging a PR.",
  },
] as const satisfies readonly ToolRegistryEntry[];

export function listToolRegistry(): ToolRegistryEntry[] {
  return TOOL_REGISTRY.map((entry) => ({
    ...entry,
    allowedChannels: entry.allowedChannels.slice(),
    requiredPermissions: entry.requiredPermissions.slice(),
    requiredEnv: entry.requiredEnv.slice(),
  }));
}

export function getToolRegistryEntry(toolId: string): ToolRegistryEntry | null {
  const entry = TOOL_REGISTRY.find((item) => item.toolId === toolId);
  if (!entry) {
    return null;
  }
  return {
    ...entry,
    allowedChannels: entry.allowedChannels.slice(),
    requiredPermissions: entry.requiredPermissions.slice(),
    requiredEnv: entry.requiredEnv.slice(),
  };
}

export function findToolsByCapability(
  capability: ToolCapability,
): ToolRegistryEntry[] {
  return listToolRegistry().filter((entry) => entry.capability === capability);
}

export function isToolForbiddenByDefault(toolId: string): boolean {
  return getToolRegistryEntry(toolId)?.forbiddenByDefault ?? true;
}
